version: '2'

services:
  www:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - db
      - postgres

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: pgdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./init-pg.sql:/docker-entrypoint-initdb.d/init.sql